apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: module-name-pv-sts

spec:
  serviceName: module-name-pv-svc

  volumeClaimTemplates:
  - metadata:
      name: module-name-XXX-pvc
    spec:
      storageClassName: nfs-client
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: storage_XXX

  replicas: num_XXX
  selector:
    matchLabels:
      app: module-name-pv-sts

  template:
    metadata:
      labels:
        app: module-name-pv-sts
    spec:
      containers:
      - image: linexus550/changeos:v1
        name: module-name
        command: ["bash", "-c"]
        args: ["cd /home/changeOS_docker && bash check_script.sh"]
        volumeMounts:
        - name: module-name-XXX-pvc
          mountPath: /home/changeOS_docker/images
        resources:
          limits:
            memory: "6Gi"
            cpu: "3"  
          requests:
            memory: "5Gi"