apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-pv-sts

spec:
  serviceName: redis-pv-svc

  volumeClaimTemplates:
  - metadata:
      name: redis-50mi-pvc
    spec:
      storageClassName: nfs-client
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Mi

  replicas: 2
  selector:
    matchLabels:
      app: redis-pv-sts

  template:
    metadata:
      labels:
        app: redis-pv-sts
    spec:
      containers:
      - image: redis:5-alpine
        name: module-name
        command: 
          # - python
          # - /path/to/model.py
        args: 
          # - --arg1
          # - value1
          # - --arg2
          # - value2
        ports: 
          - containerPort: 6379
        volumeMounts:
        - name: redis-50mi-pvc
          mountPath: /dataset